### PR TITLE
set X-Avi-Version Header

### PR DESCRIPTION
**Pull request by mu853**
The alb-virtualservice subcommand depends on the "vip" attribute of the VirtualService object introduced in 17.1.1, so the X-Avi-Version Header should be set to 17.1.1 or later.
However, if the Avi Controller version is 20.1.7 and X-Avi-Version is 20.X.X, for some reason I cannot get the vip attribute.
So, it would be better to set it to 18.2.6 at this time, according to the following document.

https://avinetworks.com/docs/20.1/release-notes/

> The minimum value for X-Avi-Version that can be used when interacting with the Avi Controller is 18.2.6. It is recommended to update the automation assets, as required.

### CODE REVIEW

**Comment by hichtakk** [comment]
Thank you for the PR. In my understanding, it might cause warning that shows using old api version. 
It would be great help if you could share which api needs the header to respond vip attribute.

**Comment by mu853** [comment]
the api is "/api/virtualservice" and is used in
https://github.com/hichtakk/nsxctl/blob/e2c39f81668ad30d5837e85d19b6172f6984f363/nsxalb/slb.go#L10

the api response is described below
https://avinetworks.com/docs/latest/api-guide/VirtualService/index.html#VirtualService

**Comment by hichtakk** [comment]
I'm just considering switch the api to "/api/virtualservice-inventory". Let's discuss the issue on zoom.

**Comment by mu853** [comment]
/api/virtualservice-inventory works fine if X-Avi-Version is set to current controller version

**Pull request merged**
